export const IMPORT_TYPES = ['usage_history', 'inventory', 'item_master', 'supplier_master', 'purchase_order', 'goods_receipt', 'sales_order', 'business_event'] as const;
export type ImportType = typeof IMPORT_TYPES[number];
export type ImportMode = 'append' | 'upsert' | 'replace';
export type ValidationSeverity = 'SUCCESS' | 'WARNING' | 'ERROR';
export type RawRow = Record<string, string | number | null>;
export type ColumnMapping = Record<string, string>;
export type ParsedImport = { rows: RawRow[]; columns: string[]; format: 'csv' | 'xlsx' };
export type ValidationError = { rowNumber: number; fieldName: string; errorCode: string; errorMessage: string; severity: Exclude<ValidationSeverity, 'SUCCESS'>; originalValue: string | number | null };
export type ValidationResult = { errors: ValidationError[]; successRows: number; warningRows: number; errorRows: number; status: ValidationSeverity };
