-- STEP4: 승인 전 staging, 행 단위 검증 오류, batch 이력을 관리합니다.
create table if not exists core.upload_batch (
  batch_id uuid primary key default gen_random_uuid(), file_name text not null, import_type text not null, import_mode text not null check (import_mode in ('append','upsert','replace')), total_rows integer not null default 0, success_rows integer not null default 0, warning_rows integer not null default 0, error_rows integer not null default 0, status text not null default 'UPLOADED' check (status in ('UPLOADED','PREVIEWED','VALIDATED','APPROVED','IMPORTED','ROLLED_BACK','FAILED')), uploaded_by uuid not null references auth.users(id), uploaded_at timestamptz not null default now(), imported_at timestamptz
);
create table if not exists core.import_staging (
  staging_id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, row_number integer not null, original_data jsonb not null, mapped_data jsonb not null, validation_status text not null default 'PENDING' check (validation_status in ('PENDING','SUCCESS','WARNING','ERROR')), created_at timestamptz not null default now(), unique(batch_id, row_number)
);
create table if not exists core.validation_error (
  validation_error_id bigint generated by default as identity primary key, batch_id uuid not null references core.upload_batch(batch_id) on delete cascade, row_number integer not null, field_name text not null, error_code text not null, error_message text not null, severity text not null check (severity in ('WARNING','ERROR')), original_value text, created_at timestamptz not null default now()
);
create table if not exists core.column_mapping (
  mapping_id bigint generated by default as identity primary key, uploaded_by uuid not null references auth.users(id), import_type text not null, source_column text not null, target_column text not null, created_at timestamptz not null default now(), unique(uploaded_by, import_type, source_column)
);

alter table core.upload_batch enable row level security;
alter table core.import_staging enable row level security;
alter table core.validation_error enable row level security;
alter table core.column_mapping enable row level security;
revoke all on core.upload_batch, core.import_staging, core.validation_error, core.column_mapping from anon;
grant select, insert, update, delete on core.upload_batch, core.import_staging, core.validation_error, core.column_mapping to authenticated;
drop policy if exists upload_batch_admin on core.upload_batch;
create policy upload_batch_admin on core.upload_batch for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists import_staging_admin on core.import_staging;
create policy import_staging_admin on core.import_staging for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists validation_error_admin on core.validation_error;
create policy validation_error_admin on core.validation_error for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists column_mapping_owner on core.column_mapping;
create policy column_mapping_owner on core.column_mapping for all to authenticated using (uploaded_by = auth.uid() or core.is_admin()) with check (uploaded_by = auth.uid() or core.is_admin());

create or replace function core.rollback_batch(target_batch_id uuid)
returns void language plpgsql security definer set search_path = core, public
as $$
declare batch core.upload_batch;
begin
  if not core.is_admin() then raise exception 'FORBIDDEN'; end if;
  select * into batch from core.upload_batch where batch_id = target_batch_id for update;
  if batch.batch_id is null then raise exception 'BATCH_NOT_FOUND'; end if;
  if batch.import_mode = 'replace' then raise exception 'REPLACE_ROLLBACK_UNSUPPORTED'; end if;
  if batch.import_type not in ('usage_history','inventory','item_master','supplier_master','purchase_order','goods_receipt','sales_order','business_event') then raise exception 'UNSUPPORTED_IMPORT_TYPE'; end if;
  execute format('delete from raw.%I where batch_id = $1', case batch.import_type when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master' when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' when 'sales_order' then 'sales_order' when 'business_event' then 'business_event' else null end) using target_batch_id;
  update core.upload_batch set status = 'ROLLED_BACK' where batch_id = target_batch_id;
end;
$$;
grant execute on function core.rollback_batch(uuid) to authenticated;

create or replace function core.import_batch(target_batch_id uuid)
returns void language plpgsql security definer set search_path = core, public
as $$
declare b core.upload_batch; table_name text; r record;
begin
  if not core.is_admin() then raise exception 'FORBIDDEN'; end if;
  select * into b from core.upload_batch where batch_id = target_batch_id for update;
  if b.batch_id is null then raise exception 'BATCH_NOT_FOUND'; end if;
  if b.status <> 'VALIDATED' then raise exception 'BATCH_NOT_VALIDATED'; end if;
  if b.error_rows > 0 then raise exception 'BATCH_HAS_VALIDATION_ERRORS'; end if;
  if b.import_mode = 'replace' then
    table_name := case b.import_type when 'usage_history' then 'usage_history' when 'inventory' then 'inventory' when 'item_master' then 'item_master' when 'supplier_master' then 'supplier_master' when 'purchase_order' then 'purchase_order' when 'goods_receipt' then 'goods_receipt' when 'sales_order' then 'sales_order' when 'business_event' then 'business_event' else null end;
    if table_name is null then raise exception 'UNSUPPORTED_IMPORT_TYPE'; end if;
    execute format('delete from raw.%I', table_name);
  end if;
  if b.import_type = 'usage_history' then
    if b.import_mode = 'upsert' then delete from raw.usage_history where source_record_id in (select coalesce(mapped_data->>'usage_id', row_number::text) from core.import_staging where batch_id = b.batch_id and validation_status = 'SUCCESS'); end if;
    insert into raw.usage_history (usage_id,item_id,use_date,qty,warehouse,note,batch_id,source_type,loaded_at,source_record_id) select coalesce(mapped_data->>'usage_id', row_number::text),mapped_data->>'item_id',nullif(mapped_data->>'use_date','')::date,nullif(mapped_data->>'qty','')::numeric,mapped_data->>'warehouse',mapped_data->>'note',b.batch_id,'FILE_UPLOAD',now(),coalesce(mapped_data->>'usage_id',row_number::text) from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'inventory' then
    if b.import_mode = 'upsert' then delete from raw.inventory where source_record_id in (select row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS'); end if;
    insert into raw.inventory ("품목코드","창고","현재고","기준일자",batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'item_id',mapped_data->>'warehouse',mapped_data->>'current_stock',mapped_data->>'inventory_date',b.batch_id,'FILE_UPLOAD',now(),row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'item_master' then
    if b.import_mode = 'upsert' then delete from raw.item_master where source_record_id in (select row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS'); end if;
    insert into raw.item_master ("품목코드","품목명","품목구분","단위",supplier_id,batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'item_id',mapped_data->>'item_name',mapped_data->>'item_type',mapped_data->>'unit',mapped_data->>'supplier_id',b.batch_id,'FILE_UPLOAD',now(),row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'supplier_master' then
    insert into raw.supplier_master ("공급업체코드","공급업체명","국가","표준리드타임(일)",batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'supplier_id',mapped_data->>'supplier_name',mapped_data->>'country',mapped_data->>'planned_lead_time',b.batch_id,'FILE_UPLOAD',now(),row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'purchase_order' then
    insert into raw.purchase_order ("발주번호","발주일","공급업체","품목코드","발주수량","납기예정일",batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'po_no',mapped_data->>'order_date',mapped_data->>'supplier_id',mapped_data->>'item_id',mapped_data->>'qty',mapped_data->>'due_date',b.batch_id,'FILE_UPLOAD',now(),row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'goods_receipt' then
    insert into raw.goods_receipt ("입고번호","발주번호","품목코드","입고수량","입고일",batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'receipt_no',mapped_data->>'po_no',mapped_data->>'item_id',mapped_data->>'receipt_qty',mapped_data->>'receipt_date',b.batch_id,'FILE_UPLOAD',now(),row_number::text from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'sales_order' then
    insert into raw.sales_order (sales_order_id,order_date,customer_id,item_id,model_base,quantity,status,batch_id,source_type,loaded_at,source_record_id) select mapped_data->>'sales_order_id',nullif(mapped_data->>'order_date','')::date,mapped_data->>'customer_id',mapped_data->>'item_id',mapped_data->>'model_base',nullif(mapped_data->>'quantity','')::numeric,mapped_data->>'status',b.batch_id,'FILE_UPLOAD',now(),coalesce(mapped_data->>'sales_order_id',row_number::text) from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  elsif b.import_type = 'business_event' then
    insert into raw.business_event (event_id,event_type,event_date,item_id,model_base,quantity,attributes,batch_id,source_type,loaded_at,source_record_id) select coalesce(mapped_data->>'event_id',row_number::text),mapped_data->>'event_type',nullif(mapped_data->>'event_date','')::date,mapped_data->>'item_id',mapped_data->>'model_base',nullif(mapped_data->>'quantity','')::numeric,mapped_data->'attributes',b.batch_id,'FILE_UPLOAD',now(),coalesce(mapped_data->>'event_id',row_number::text) from core.import_staging where batch_id=b.batch_id and validation_status='SUCCESS';
  else raise exception 'UNSUPPORTED_IMPORT_TYPE'; end if;
  update core.upload_batch set status='IMPORTED', imported_at=now() where batch_id=b.batch_id;
end;
$$;
grant execute on function core.import_batch(uuid) to authenticated;
