-- STEP3: 적재 추적, 운영 정책, 학습/검증 기간을 추가합니다.
-- 기존 raw 테이블은 삭제하거나 재생성하지 않습니다.

do $$
declare table_name text;
begin
  foreach table_name in array array['shipment_log','supplier_master','item_master','inventory','usage_history','forecast','goods_receipt','purchase_order','dim_item','dim_model','fact_shipment','fact_mc_plan_actual','bridge_bom','bridge_scc_config','bridge_mc_cap','bridge_cap_option','bridge_option_model','bridge_xcn'] loop
    if to_regclass(format('raw.%I', table_name)) is not null then
      execute format('alter table raw.%I add column if not exists batch_id uuid', table_name);
      execute format('alter table raw.%I add column if not exists source_type text', table_name);
      execute format('alter table raw.%I add column if not exists loaded_at timestamptz default now()', table_name);
      execute format('alter table raw.%I add column if not exists source_record_id text', table_name);
    end if;
  end loop;
end $$;

create table if not exists raw.business_event (
  event_id text primary key,
  event_type text not null,
  event_date date,
  item_id text,
  model_base text,
  quantity numeric,
  attributes jsonb,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz not null default now(),
  source_record_id text
);
create table if not exists raw.sales_order (
  sales_order_id text primary key,
  order_date date,
  customer_id text,
  item_id text,
  model_base text,
  quantity numeric,
  status text,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz not null default now(),
  source_record_id text
);
create table if not exists raw.item_substitute (
  item_substitute_id bigint generated by default as identity primary key,
  item_id text not null,
  substitute_item_id text not null,
  priority integer,
  active boolean not null default true,
  batch_id uuid,
  source_type text,
  loaded_at timestamptz not null default now(),
  source_record_id text,
  unique (item_id, substitute_item_id)
);

create table if not exists core.policy_config (
  config_key text primary key,
  service_level numeric,
  review_period_days integer,
  safety_buffer_days numeric,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists core.outlier_rule (
  rule_id bigint generated by default as identity primary key,
  rule_code text not null unique,
  description text,
  exclusion_type text not null check (exclusion_type in ('PROJECT','RETURN','DUPLICATE','OTHER')),
  conditions jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists core.item_policy (
  item_id text primary key,
  moq numeric,
  pack_size numeric,
  item_grade text,
  service_level numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists core.forecast_setting (
  setting_id smallint primary key default 1 check (setting_id = 1),
  train_start date not null,
  train_end date not null,
  test_start date not null,
  test_end date not null,
  granularity text not null default 'DAY' check (granularity in ('DAY','WEEK','MONTH')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (train_start <= train_end and test_start <= test_end and train_end < test_start)
);

create or replace view core.v_train_demand as
select u.usage_id, upper(regexp_replace(u.item_id, '[\s\-_]', '', 'g')) as item_id, u.use_date, u.qty, u.warehouse, u.note
from raw.usage_history u
cross join (select train_start, train_end from core.forecast_setting where active order by setting_id limit 1) s
where u.use_date between s.train_start and s.train_end;

create or replace view core.v_test_actual as
select u.usage_id, upper(regexp_replace(u.item_id, '[\s\-_]', '', 'g')) as item_id, u.use_date, u.qty, u.warehouse, u.note
from raw.usage_history u
cross join (select test_start, test_end from core.forecast_setting where active order by setting_id limit 1) s
where u.use_date between s.test_start and s.test_end;

create or replace view core.v_usage_effective as
with calc as (
  select item_id, count(*) as valid_days, round(avg(qty), 2) as daily_usage_avg, round(stddev_samp(qty), 2) as daily_usage_sd
  from core.v_train_demand
  where qty >= 0 and coalesce(note, '') not ilike '%프로젝트%'
  group by item_id
)
select c.item_id, coalesce(p.valid_days::bigint, c.valid_days) as valid_days,
  coalesce(p.daily_usage_avg, c.daily_usage_avg) as daily_usage_avg,
  coalesce(p.daily_usage_sd, c.daily_usage_sd) as daily_usage_sd,
  round(coalesce(p.daily_usage_avg, c.daily_usage_avg), 2) as usage_used,
  round(coalesce(p.daily_usage_sd, c.daily_usage_sd) / nullif(coalesce(p.daily_usage_avg, c.daily_usage_avg), 0), 2) as cv,
  case when p.item_id is not null then '확정값' else '학습 기간 정제값' end as source
from calc c left join core.usage_profile p on p.item_id = c.item_id;

create or replace view analytics.v_data_coverage as
with bounds as (select min(use_date) as data_start, max(use_date) as data_end, count(*) as total_rows from raw.usage_history),
setting as (select * from core.forecast_setting where active order by setting_id limit 1),
train as (select count(*) as row_count from core.v_train_demand),
test as (select count(*) as row_count from core.v_test_actual)
select b.data_start, b.data_end, s.train_start, s.train_end, s.test_start, s.test_end,
  coalesce(t.row_count, 0) as train_row_count, coalesce(x.row_count, 0) as test_row_count,
  (s.train_start is not null and b.data_start <= s.train_start and b.data_end >= s.train_end) as train_window_ok,
  (s.test_start is not null and b.data_start <= s.test_start and b.data_end >= s.test_end) as test_window_ok,
  b.total_rows
from bounds b left join setting s on true cross join train t cross join test x;

create or replace view analytics.v_forecast_setting_summary as
select c.*, (select jsonb_agg(to_jsonb(p) order by p.config_key) from core.policy_config p) as policy_values,
  (select count(*) from core.item_policy) as item_policy_count,
  (select count(*) from core.outlier_rule where enabled) as enabled_outlier_rule_count
from analytics.v_data_coverage c;

alter table raw.business_event enable row level security;
alter table raw.sales_order enable row level security;
alter table raw.item_substitute enable row level security;
revoke all on raw.business_event, raw.sales_order, raw.item_substitute from anon, authenticated;

alter table core.policy_config enable row level security;
alter table core.outlier_rule enable row level security;
alter table core.item_policy enable row level security;
alter table core.forecast_setting enable row level security;
grant select, insert, update, delete on core.policy_config, core.outlier_rule, core.item_policy, core.forecast_setting to authenticated;
drop policy if exists policy_config_read on core.policy_config;
create policy policy_config_read on core.policy_config for select to authenticated using (auth.uid() is not null);
drop policy if exists policy_config_admin_write on core.policy_config;
create policy policy_config_admin_write on core.policy_config for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists outlier_rule_read on core.outlier_rule;
create policy outlier_rule_read on core.outlier_rule for select to authenticated using (auth.uid() is not null);
drop policy if exists outlier_rule_admin_write on core.outlier_rule;
create policy outlier_rule_admin_write on core.outlier_rule for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists item_policy_read on core.item_policy;
create policy item_policy_read on core.item_policy for select to authenticated using (auth.uid() is not null);
drop policy if exists item_policy_admin_write on core.item_policy;
create policy item_policy_admin_write on core.item_policy for all to authenticated using (core.is_admin()) with check (core.is_admin());
drop policy if exists forecast_setting_read on core.forecast_setting;
create policy forecast_setting_read on core.forecast_setting for select to authenticated using (auth.uid() is not null);
drop policy if exists forecast_setting_admin_write on core.forecast_setting;
create policy forecast_setting_admin_write on core.forecast_setting for all to authenticated using (core.is_admin()) with check (core.is_admin());

grant select on core.v_train_demand, core.v_test_actual to authenticated;
grant select on analytics.v_data_coverage, analytics.v_forecast_setting_summary to authenticated;
