create schema if not exists core;
do $$ begin create type core.app_role as enum ('ADMIN', 'USER'); exception when duplicate_object then null; end $$;
create table if not exists core.app_user (user_id uuid primary key references auth.users(id) on delete cascade, email text not null, name text, department text, role core.app_role not null default 'USER', active boolean not null default true, last_login_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists core.audit_log (id bigint generated by default as identity primary key, actor uuid references auth.users(id) on delete set null, action text not null, target_type text not null, target_id text not null, before jsonb, after jsonb, at timestamptz not null default now());
create or replace function core.is_admin() returns boolean language sql stable security definer set search_path = core, public as $$ select exists (select 1 from core.app_user where user_id = auth.uid() and role = 'ADMIN' and active); $$;
create or replace function core.handle_new_user() returns trigger language plpgsql security definer set search_path = core, public as $$ begin insert into core.app_user(user_id, email, name) values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'name', '')); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function core.handle_new_user();
create or replace function core.touch_app_user() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists app_user_updated_at on core.app_user;
create trigger app_user_updated_at before update on core.app_user for each row execute function core.touch_app_user();
alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
revoke all on core.app_user, core.audit_log from anon;
revoke insert, update, delete on core.app_user, core.audit_log from authenticated;
grant select on core.app_user to authenticated;
grant insert on core.audit_log to authenticated;
drop policy if exists app_user_select on core.app_user;
create policy app_user_select on core.app_user for select to authenticated using (user_id = auth.uid() or core.is_admin());
drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update on core.app_user for update to authenticated using (core.is_admin() and user_id <> auth.uid()) with check (core.is_admin() and user_id <> auth.uid());
drop policy if exists audit_log_admin_insert on core.audit_log;
create policy audit_log_admin_insert on core.audit_log for insert to authenticated with check (core.is_admin() and actor = auth.uid());

create or replace function core.record_login()
returns void language sql security definer set search_path = core, public
as $$ update core.app_user set last_login_at = now() where user_id = auth.uid(); $$;
grant execute on function core.record_login() to authenticated;

create or replace function core.admin_update_app_user(target_user_id uuid, next_role core.app_role, next_active boolean)
returns jsonb language plpgsql security definer set search_path = core, public
as $$
declare old_row jsonb; new_row jsonb;
begin
  if not core.is_admin() then raise exception 'FORBIDDEN'; end if;
  if target_user_id = auth.uid() then raise exception 'SELF_UPDATE_FORBIDDEN'; end if;
  select to_jsonb(u) into old_row from core.app_user u where u.user_id = target_user_id for update;
  if old_row is null then raise exception 'USER_NOT_FOUND'; end if;
  update core.app_user set role = next_role, active = next_active where user_id = target_user_id returning to_jsonb(core.app_user) into new_row;
  insert into core.audit_log(actor, action, target_type, target_id, before, after) values (auth.uid(), 'USER_ACCESS_UPDATED', 'app_user', target_user_id::text, old_row, new_row);
  return new_row;
end;
$$;
grant execute on function core.admin_update_app_user(uuid, core.app_role, boolean) to authenticated;

revoke all on all tables in schema core from anon;
revoke all on all tables in schema analytics from anon;
